### ISSUE TITLE
Why not using nuget package for sciBASIC#

### ISSUE THREAD

**Issue by weianweigan** [xieguigang/mzkit#16]
**Describe the solution you'd like**
Some suggestions about this handsome repository:
I found that a nuget package published about [sciBASIC#](https://github.com/xieguigang/sciBASIC).Why not using nuget package for sciBASIC#?It's a little comflex to compile this project.
I am confused that so many *.sln existed in this repository.At the same time,there is some *.sln which ended with NET5 or netcore5.It' easy to use new [sdk style](https://zhuanlan.zhihu.com/p/408933763) *.vbproj to support muti-framework and corss-platform. 

![image](https://user-images.githubusercontent.com/25452811/179677869-21a827b2-caf4-41f1-8680-da9db2fdcda2.png)

**Describe alternatives you've considered**
Use nuget to simplify repository structure；
Use new sdk style *vbproj that supports more targetFrameworks;

**Additional context**
Some refer:
[targetFrameworks](https://docs.microsoft.com/zh-cn/dotnet/standard/frameworks)
![image](https://user-images.githubusercontent.com/25452811/179678463-0cdabe8e-d98b-4822-8e61-8f0aafbbd6cb.png)

**Comment by xieguigang** [comment]
hi, many thanks to the advice about the development project. 

since the commit [5cb01d2f3349f89eec6efbe6474c6a064a11da6d](https://github.com/xieguigang/mzkit/tree/5cb01d2f3349f89eec6efbe6474c6a064a11da6d)(2022/04), all of the mzkit library source project is already been switched to the new .NET sdk format. example as [mzkit.NET5.vbproj](https://github.com/xieguigang/mzkit/blame/5cb01d2f3349f89eec6efbe6474c6a064a11da6d/Rscript/Library/mzkit/mzkit.NET5.vbproj):

```xml
<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<RootNamespace>mzkit</RootNamespace>
		<TargetFrameworks>net6.0;net5.0;net48</TargetFrameworks>
		<AssemblyName>mzkit</AssemblyName>
		<Platforms>AnyCPU;x64</Platforms>
		<Configurations>Debug;Release;LipidSearch;PlantMAT;mzkit;Rsharp_app_release</Configurations>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<Authors>xieguigang</Authors>
		<Company>BioNovoGene</Company>
		<Product>BioDeep</Product>
		<PackageLicenseFile>LICENSE</PackageLicenseFile>
		<PackageProjectUrl>http://mzkit.org</PackageProjectUrl>
		<PackageIcon>Flask.png</PackageIcon>
		<PackageIconUrl />
		<RuntimeIdentifiers>win7-x64;win7-x86;win-x64;linux-x64;linux-arm64;osx-x64</RuntimeIdentifiers>
	</PropertyGroup>

...
```

due to the reason of frequently update of the base library source code(example as the sciBASIC.NET, GCModeller, R# language interpreter), it is not a good choice for use the nuget package as update the nuget package frequently will increase the extra workload.

**Comment by weianweigan** [comment]
Thanks for your reply!
Yes, there is some extra work.In another side, it will make a good workflow and make project more healthy.
Now, it's so hard that when a new coder wants to join or make some contributions.
I cannot compile it and feel big head with so many *.sln although with your help from bilibili.  
It's a good opensource cad software. It will be better if other developers can join it quickly.

**Comment by xieguigang** [comment]
Hi, many thanks for interesting in mzkit project. Here is the document for introduce how to compile the mzkit project: https://github.com/xieguigang/mzkit_win32

**Comment by weianweigan** [comment]
> Hi, many thanks for interesting in mzkit project. Here is the document for introduce how to compile the mzkit project: https://github.com/xieguigang/mzkit_win32

It's a big help, I will take a try.
